debugging

diff --git a/.github/workflows/terraform-cmms.yml b/.github/workflows/terraform-cmms.yml
--- a/.github/workflows/terraform-cmms.yml
+++ b/.github/workflows/terraform-cmms.yml
@@ -88,23 +88,22 @@ jobs:
         POSTGRES_INSTANCE: ${{ vars.POSTGRES_INSTANCE }}
         POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
       working-directory: ${{ env.GCLOUD_MODULE_PATH }}
-      run: >
-        terraform plan 
-        -input=false 
-        -detailed-exitcode 
-        -out=tfplan 
-        -var="key_ring_name=$KEY_RING" 
-        -var="spanner_instance_name=$SPANNER_INSTANCE" 
-        -var="spanner_processing_units=$SPANNER_PROCESSING_UNITS" 
-        -var="storage_bucket_name=$STORAGE_BUCKET" 
-        -var="secure_computation_storage_bucket_name=$SECURE_COMPUTATION_BUCKET" 
-        -var="terraform_service_account=$TERRAFORM_SERVICE_ACCOUNT" 
-        -var="postgres_instance_name=$POSTGRES_INSTANCE" 
-        -var="postgres_password=$POSTGRES_PASSWORD" || exit_code=$?
-        if [ "${exit_code:-0}" -eq 0 ]; 
+      run: |
+        set -o errexit    # fail fast
+        set -o pipefail   # catch pipeline errors
+
+        exit_code=0
+        terraform plan \
+          -input=false \
+          -detailed-exitcode \
+          -out=tfplan \
+          -var="key_ring_name=$KEY_RING" \
+          … || exit_code=$?
+
+        if [ "$exit_code" -eq 0 ]; then
           echo "No changes."
-        elif [ "${exit_code:-0}" -eq 2 ]; 
-          echo "ℹChanges detected."
+        elif [ "$exit_code" -eq 2 ]; then
+          echo "ℹ Changes detected."
         else
           echo "Terraform plan failed."
           exit $exit_code
