debugging

diff --git a/.github/workflows/terraform-cmms.yml b/.github/workflows/terraform-cmms.yml
--- a/.github/workflows/terraform-cmms.yml
+++ b/.github/workflows/terraform-cmms.yml
@@ -88,9 +88,10 @@ jobs:
         POSTGRES_INSTANCE: ${{ vars.POSTGRES_INSTANCE }}
         POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
       working-directory: ${{ env.GCLOUD_MODULE_PATH }}
+      continue-on-error: true
       run: |
-        set -o errexit    # fail fast
-        set -o pipefail   # catch pipeline errors
+#        set -o errexit    # fail fast
+#        set -o pipefail   # catch pipeline errors
 
         exit_code=0
         terraform plan \
@@ -104,16 +105,16 @@ jobs:
           -var="secure_computation_storage_bucket_name=$SECURE_COMPUTATION_BUCKET" \
           -var="terraform_service_account=$TERRAFORM_SERVICE_ACCOUNT" \
           -var="postgres_instance_name=$POSTGRES_INSTANCE" \
-          -var="postgres_password=$POSTGRES_PASSWORD" || exit_code=$?
-
-        if [ "$exit_code" -eq 0 ]; then
-          echo "No changes."
-        elif [ "$exit_code" -eq 2 ]; then
-          echo "ℹ Changes detected."
-        else
-          echo "Terraform plan failed."
-          exit $exit_code
-        fi
+          -var="postgres_password=$POSTGRES_PASSWORD"
+#  || exit_code=$?
+#        if [ "$exit_code" -eq 0 ]; then
+#          echo "No changes."
+#        elif [ "$exit_code" -eq 2 ]; then
+#          echo "ℹ Changes detected."
+#        else
+#          echo "Terraform plan failed."
+#          exit $exit_code
+#        fi
 
     - name: terraform apply -auto-approve - gcloud
       if: ${{ inputs.apply }}
